/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.automatizado;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author RICARDO
 */



public class Ventana extends javax.swing.JFrame{

    /**
     * Creates new form Ventana
     */
    
     /*Varibale auxiliar*/
    //public PlantaFisica auxPlantaFisica = new PlantaFisica();
    public Asignatura auxAsignaturas;
    public BackgroundMenuBar menucolor;
    
    /*Listas de objetos principales*/
    public ArrayList<PlantaFisica> listaPlantaFisica = new ArrayList<PlantaFisica>();
    public ArrayList<Asignatura> listaAsignaturas = new ArrayList<Asignatura>();
    public ArrayList<Docente> listaDocente = new ArrayList<Docente>();
    public ArrayList<Oferta> listaOferta = new ArrayList<Oferta>();
    
    public static Usuario usuario;
    public VentanaOfertaAcademica ventanaofertaacademica = new VentanaOfertaAcademica(this);
    public VentanaSabana ventanasabana = new VentanaSabana(this);
    public VentanaPlantaFisica ventanaplantafisica = new VentanaPlantaFisica(this);
    public VentanaAsignatura ventanaAsignaturas = new VentanaAsignatura(this);
    public VentanaDocente ventanadocente = new VentanaDocente(this);
    
    
    
    public Ventana() {
        initComponents();
        
        Image icono = Toolkit.getDefaultToolkit().getImage("logo.png");
        this.setIconImage(icono);
        this.setTitle("Inicio");
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(255,255,255));
        jMenuBar1.setOpaque(true);
        jMenuBar1.setBorderPainted(false);
       
        
        //Aspecto inicial del panel
        jScrollPane1.setBorder(null);     
        panelAyuda.setVisible(false);
        panelAyuda.setBackground(new java.awt.Color(255,255,255));
        
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        btnHorario = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnOfertaAcademica = new javax.swing.JButton();
        btnSabana = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        panelAyuda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAyuda = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuPlantaFisica = new javax.swing.JMenuItem();
        menuAsignaturas = new javax.swing.JMenuItem();
        menuDocentes = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(13, 80, 175));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 41));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHorario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnHorario.setForeground(new java.awt.Color(255, 255, 255));
        btnHorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/lapiz.png"))); // NOI18N
        btnHorario.setText("CREAR HORARIO");
        btnHorario.setContentAreaFilled(false);
        btnHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHorarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHorarioMouseExited(evt);
            }
        });
        btnHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 240, 41));

        btnReporte.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/sticky.png"))); // NOI18N
        btnReporte.setText("GENERAR REPORTE");
        btnReporte.setContentAreaFilled(false);
        btnReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReporteMouseExited(evt);
            }
        });
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel1.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 240, 40));

        btnOfertaAcademica.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnOfertaAcademica.setForeground(new java.awt.Color(255, 255, 255));
        btnOfertaAcademica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/refresh-32.png"))); // NOI18N
        btnOfertaAcademica.setText("OFERTA ACADEMICA");
        btnOfertaAcademica.setContentAreaFilled(false);
        btnOfertaAcademica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOfertaAcademicaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOfertaAcademicaMouseExited(evt);
            }
        });
        btnOfertaAcademica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfertaAcademicaActionPerformed(evt);
            }
        });
        jPanel1.add(btnOfertaAcademica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        btnSabana.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSabana.setForeground(new java.awt.Color(255, 255, 255));
        btnSabana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/lapiz.png"))); // NOI18N
        btnSabana.setText("DISEÑAR SABANA");
        btnSabana.setContentAreaFilled(false);
        btnSabana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSabanaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSabanaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSabanaMouseExited(evt);
            }
        });
        btnSabana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSabanaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSabana, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 240, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 970, -1));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logotipo_3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(60, 141, 188));
        jLabel4.setText("NombreUsuario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 119, -1));

        btnSalir.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(60, 141, 188));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/account-log-in-48.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 136, -1));

        txtAyuda.setColumns(20);
        txtAyuda.setLineWrap(true);
        txtAyuda.setRows(5);
        txtAyuda.setText("\n");
        txtAyuda.setBorder(null);
        jScrollPane1.setViewportView(txtAyuda);

        javax.swing.GroupLayout panelAyudaLayout = new javax.swing.GroupLayout(panelAyuda);
        panelAyuda.setLayout(panelAyudaLayout);
        panelAyudaLayout.setHorizontalGroup(
            panelAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAyudaLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panelAyudaLayout.setVerticalGroup(
            panelAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAyudaLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        getContentPane().add(panelAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 930, 250));

        jMenu7.setText("Archivo");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Save_1.png"))); // NOI18N
        jMenuItem6.setText("Guardar");
        jMenu7.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/reply-16.png"))); // NOI18N
        jMenuItem7.setText("Deshacer");
        jMenu7.add(jMenuItem7);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/77-24.png"))); // NOI18N
        jMenuItem8.setText("Borrar todo");
        jMenu7.add(jMenuItem8);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/refresh-32_2.png"))); // NOI18N
        jMenuItem2.setText("Cargar data");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem2);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/lapiz_2.png"))); // NOI18N
        jMenuItem10.setText("Crear sabana");
        jMenu7.add(jMenuItem10);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Acerca de");

        jMenuItem9.setText("Ayuda");
        jMenu8.add(jMenuItem9);

        jMenuItem5.setText("Quienes Somos");
        jMenu8.add(jMenuItem5);

        jMenuBar1.add(jMenu8);

        jMenu1.setText("Listado");

        menuPlantaFisica.setText("Planta Física");
        menuPlantaFisica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuPlantaFisicaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuPlantaFisicaMouseExited(evt);
            }
        });
        menuPlantaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPlantaFisicaActionPerformed(evt);
            }
        });
        jMenu1.add(menuPlantaFisica);

        menuAsignaturas.setText("Asignatura");
        menuAsignaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuAsignaturasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuAsignaturasMouseExited(evt);
            }
        });
        menuAsignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAsignaturasActionPerformed(evt);
            }
        });
        jMenu1.add(menuAsignaturas);

        menuDocentes.setText("Docente");
        menuDocentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuDocentesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuDocentesMouseExited(evt);
            }
        });
        menuDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDocentesActionPerformed(evt);
            }
        });
        jMenu1.add(menuDocentes);

        jMenuBar1.add(jMenu1);

        jMenu6.setText("Salir");

        jMenuItem4.setText("Cerrar Sesión");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuItem3.setText("Cerrar Ventana");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        jMenuBar1.add(jMenu6);

        setBackground(Color.BLUE);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void cargarDatos(){
        jLabel4.setText(usuario.getNombre());    
        jLabel2.show(true);
        jLabel4.show(true);
    
    }
    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane,"Campo vacío", "ADVERTENCIA", 0);
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnOfertaAcademicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfertaAcademicaActionPerformed
        // TODO add your handling code here:
        
        
        // obtener la lista oferta para cargarla en la tabla, el problema es que no se a la hora de poner cuantas secciones y eso
        listaOferta = OperacionesBD.getOferta(usuario.getNombre(), usuario.getClave());
       
        
        if(listaOferta!=null){
            
            ventanaofertaacademica.usuario = new Usuario();      
            ventanaofertaacademica.usuario.setNombre(usuario.getNombre());
            ventanaofertaacademica.usuario.setClave(usuario.getClave());
            ventanaofertaacademica.cargar(usuario.getNombre(), usuario.getClave()); 
            ventanaofertaacademica.limpiar();
            ventanaofertaacademica.setVisible(true);
            
            //ok recuerda q siempre para todas las ventanas debes hacer lo usuario osea esto y esto
            
        }
        
    }//GEN-LAST:event_btnOfertaAcademicaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnSabanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSabanaActionPerformed
        //jButton3.setToolTipText("Informacion");
        
        listaOferta = OperacionesBD.getOferta(usuario.getNombre(), usuario.getClave());
        
        //JOptionPane.showMessageDialog(this, listaOferta.get(0).getAsignatura());
        
        if(listaOferta!=null){
            ventanasabana.usuario = new Usuario();      
            ventanasabana.usuario.setNombre(usuario.getNombre());
            ventanasabana.usuario.setClave(usuario.getClave());
            ventanasabana.limpiar();
            ventanasabana.cargarInfo(usuario.getNombre(), usuario.getClave());
            ventanasabana.cargarAsig(usuario.getNombre(), usuario.getClave());
            ventanasabana.setVisible(true);
        }
    }//GEN-LAST:event_btnSabanaActionPerformed
   
    private void menuPlantaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPlantaFisicaActionPerformed

        
        listaPlantaFisica = OperacionesBD.getAulas(usuario.getNombre(), usuario.getClave());
        
        ventanaplantafisica.cargar();
        ventanaplantafisica.setVisible(true);
    }//GEN-LAST:event_menuPlantaFisicaActionPerformed

    private void menuAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAsignaturasActionPerformed
        // TODO add your handling code here:
 
        //Se oculta el panel de ayuda
        panelAyuda.setVisible(false);
        
        listaAsignaturas = OperacionesBD.getAsignaturas(usuario.getNombre(), usuario.getClave());
        
        if(listaAsignaturas!=null){
            ventanaAsignaturas.usuario = new Usuario();
            ventanaAsignaturas.usuario.setNombre(usuario.getNombre());
            ventanaAsignaturas.usuario.setClave(usuario.getClave());
            ventanaAsignaturas.cargar();
            ventanaAsignaturas.setVisible(true);
        }
        
    }//GEN-LAST:event_menuAsignaturasActionPerformed

    private void btnHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorarioActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane,"Campo vacío", "ADVERTENCIA", 0);
    }//GEN-LAST:event_btnHorarioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        String args[] = null;
        VentanaInicio.main(args);

        this.dispose();

    }//GEN-LAST:event_btnSalirActionPerformed

    private void menuDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDocentesActionPerformed
        // TODO add your handling code here:
       
        //Se oculta el panel de ayuda
        panelAyuda.setVisible(false);
        
        //listaDocente.add(auxDocente);
        listaDocente = OperacionesBD.getDocentes(usuario.getNombre(), usuario.getClave());
        
        if(listaDocente!=null){
            ventanadocente.cargar();
            ventanadocente.setVisible(true);
        }
        
        
    }//GEN-LAST:event_menuDocentesActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        String args[] = null;
        VentanaInicio.main(args);

        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnOfertaAcademicaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOfertaAcademicaMouseEntered
        // TODO add your handling code here:
        panelAyuda.setVisible(true);
        txtAyuda.setText("Se basa en organizar las asignaturas por semestre. Dichas asignaturas poseen sus respectivos profesores, y los semestres sus respectivas \n secciones, todo esto viene determinado por la demanda estudiantil para el periodo indicado.");
    }//GEN-LAST:event_btnOfertaAcademicaMouseEntered

    private void btnOfertaAcademicaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOfertaAcademicaMouseExited
        //Se oculta el panel de ayuda
        panelAyuda.setVisible(false);
    }//GEN-LAST:event_btnOfertaAcademicaMouseExited

    private void btnSabanaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSabanaMouseEntered
        // TODO add your handling code here:
        panelAyuda.setVisible(true);
        txtAyuda.setText("Una sabana es diseñada para una carrera en especifico, y cada carrera posee una unica sabana por semestre.\n"
                +"En una carrera se necesita conocer la sabana por semestre ademas de la planificacion hacia las materias extracurriculares.");
    }//GEN-LAST:event_btnSabanaMouseEntered

    private void btnSabanaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSabanaMouseExited
        //Se oculta el panel de ayuda
        panelAyuda.setVisible(false);
    }//GEN-LAST:event_btnSabanaMouseExited

    private void btnHorarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHorarioMouseEntered
        // TODO add your handling code here:
        panelAyuda.setVisible(true);
        txtAyuda.setText("\tLos horarios se generan de la Sabana, dichos horarios son listados y ordenados por niveles");
    }//GEN-LAST:event_btnHorarioMouseEntered

    private void btnHorarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHorarioMouseExited
        //Se oculta el panel de ayuda
        panelAyuda.setVisible(false);
    }//GEN-LAST:event_btnHorarioMouseExited

    private void btnReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMouseEntered
        // TODO add your handling code here:
        panelAyuda.setVisible(true);
        txtAyuda.setText("ESTA EN VEREMOS");
    }//GEN-LAST:event_btnReporteMouseEntered

    private void btnReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMouseExited
        //Se oculta el panel de ayuda
        panelAyuda.setVisible(false);
    }//GEN-LAST:event_btnReporteMouseExited

    private void menuAsignaturasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAsignaturasMouseEntered
        // TODO add your handling code here:
        panelAyuda.setVisible(true);
        txtAyuda.setText("Cada asignatura está asignada a un departamento y a su vez cada departamento pertenece a un área.\n"
                            +"Cada asignatura tiene Unidades de Crédito (UC) que oscilan entre 1 y 4, y tienen números de horas por semana que oscilan entre 2 y 7 horas.\n"
                            +"Por cada materia se abren un número de secciones por semestre y el número de secciones dependerá de la demanda de estudiantes.\n"
                            +"Estos datos pueden ser flexibles de modificación.\n"
                            +"Una materia puede prelar a otra materia y una materia puede ser prelada por otra.");
    }//GEN-LAST:event_menuAsignaturasMouseEntered

    private void menuAsignaturasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAsignaturasMouseExited
        //Se oculta el panel de ayuda
        panelAyuda.setVisible(false);
    }//GEN-LAST:event_menuAsignaturasMouseExited

    private void menuDocentesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDocentesMouseEntered
        // TODO add your handling code here:
        panelAyuda.setVisible(true);
        txtAyuda.setText("Una asignatura es dictada por un profesor y varias secciones de la misma asignatura pueden ser dictadas por el mismo docente siempre y cuando los horarios lo permitan.\n"
                            + "El número de asignaturas que puede dictar un profesor está relacionado con su dedicación");
    }//GEN-LAST:event_menuDocentesMouseEntered

    private void menuDocentesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDocentesMouseExited
        //Se oculta el panel de ayuda
        panelAyuda.setVisible(false);
    }//GEN-LAST:event_menuDocentesMouseExited

    private void menuPlantaFisicaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPlantaFisicaMouseEntered
        // TODO add your handling code here:
        panelAyuda.setVisible(true);
        txtAyuda.setText("\tLa universidad cuenta actualmente con aulas y laboratorios, además del salon de usos multiples\n");
    }//GEN-LAST:event_menuPlantaFisicaMouseEntered

    private void menuPlantaFisicaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPlantaFisicaMouseExited
        //Se oculta el panel de ayuda
        panelAyuda.setVisible(false);
    }//GEN-LAST:event_menuPlantaFisicaMouseExited

    private void btnSabanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSabanaMouseClicked
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_btnSabanaMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHorario;
    private javax.swing.JButton btnOfertaAcademica;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSabana;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuAsignaturas;
    private javax.swing.JMenuItem menuDocentes;
    private javax.swing.JMenuItem menuPlantaFisica;
    private javax.swing.JPanel panelAyuda;
    private javax.swing.JTextArea txtAyuda;
    // End of variables declaration//GEN-END:variables

   

   
}
